### ISSUE TITLE
[Future Plan][Other Languages]

### ISSUE THREAD

**Issue by sara-02** [deniederhut/niacin#17]
Hey, @deniederhut just curious to know if you plan on adding other languages as well?
If so how are you planning on obtaining the modification data for the same?
Asking because it will incur changes in the way we are currently storing/loading the data used modification.
Also, do we have any reference literature or experiments done in languages other than English to show whether these transformations are as effective as they seem to be for English?

P.S: This is not w.r.t to the review, asking just out of curiosity.

**Comment by deniederhut** [comment]
That's a great question! My research has all been in English, so that's where the library went. I'm sure someone is doing research in data augmentation in other languages, especially since it's more useful in low-resource settings than it is for languages with lots and lots of data to be had.

As for effectiveness, you could imagine that whitespace modifications might help less in agglutinative languages like German; or, that word order changes would be more helpful for a language with strong verb cases like Turkish. Things like adding random symbols (typically done from ascii) would likely be unhelpful for languages with a different character set like Tamil. Even within the Latin alphabet, the keyboard distances are different for a language like French. But this is all speculation.

That said, I don't have any concrete plans for adding a specific language at the moment. I suppose I am waiting for someone to be like "Hey dude nice library you got there but my research is in ______".
